import { precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const sw = self as any;

sw.addEventListener("message", (event: ExtendableMessageEvent) => {
  if (event.data?.type === "SKIP_WAITING") {
    void self.skipWaiting();
  }
});

// Handle push notifications
sw.addEventListener("push", (event: any) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || "Finlo";
    const options = {
      body: data.body || "New update in your ledger",
      icon: "/icons/icon-192.png",
      badge: "/icons/icon-192.png",
      data: data.url || "/",
      vibrate: [100, 50, 100],
      tag: data.tag || "general",
      renotify: true,
      actions: [
        { action: "view", title: "View Details" },
        { action: "close", title: "Dismiss" }
      ]
    };

    event.waitUntil(sw.registration.showNotification(title, options));
  } catch (err) {
    console.error("Push event error:", err);
  }
});

// Handle notification clicks
sw.addEventListener("notificationclick", (event: any) => {
  event.notification.close();

  if (event.action === "close") return;

  const raw = event.notification.data || "/";
  const urlToOpen = raw.startsWith("http") ? raw : `${self.location.origin}${raw.startsWith("/") ? raw : `/${raw}`}`;

  event.waitUntil(
    sw.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients: any[]) => {
      for (const client of windowClients) {
        if ("focus" in client) {
          if ("navigate" in client && typeof client.navigate === "function") {
            return client.navigate(urlToOpen).then(() => client.focus());
          }
          return client.focus();
        }
      }
      if (sw.clients.openWindow) {
        return sw.clients.openWindow(urlToOpen);
      }
    }),
  );
});
