import { precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const sw = self as any;

// Handle push notifications
sw.addEventListener("push", (event: any) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || "Finlo";
    const options = {
      body: data.body || "New update in your ledger",
      icon: "/icons/icon-192.png",
      badge: "/icons/icon-192.png",
      data: data.url || "/",
      vibrate: [100, 50, 100],
      tag: data.tag || "general",
      renotify: true,
      actions: [
        { action: "view", title: "View Details" },
        { action: "close", title: "Dismiss" }
      ]
    };

    event.waitUntil(sw.registration.showNotification(title, options));
  } catch (err) {
    console.error("Push event error:", err);
  }
});

// Handle notification clicks
sw.addEventListener("notificationclick", (event: any) => {
  event.notification.close();

  if (event.action === "close") return;

  const urlToOpen = event.notification.data || "/";

  event.waitUntil(
    sw.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients: any[]) => {
      // If a window is already open, focus it
      for (const client of windowClients) {
        if (client.url.includes(urlToOpen) && "focus" in client) {
          return client.focus();
        }
      }
      // Otherwise open a new window
      if (sw.clients.openWindow) {
        return sw.clients.openWindow(urlToOpen);
      }
    })
  );
});
